<?php
$securitySettings_var = array( 'providers' => array( array( 'type' => '%db',
'activationField' => 'active',
'active' => true,
'code' => '00',
'emailField' => 'email',
'extUserIdField' => 'ext_security_id',
'fullnameField' => 'fullname',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'resetDateField' => '˂Create new˃',
'resetTokenField' => '˂Create new˃',
'table' => array( 'connId' => 'fhaddcom_finance_at_localhost',
'table' => 'tbl_users' ),
'userGroupField' => 'ID',
'usernameField' => 'username',
'userpicField' => 'userpic' ),
array( 'scope' => 'openid profile email ',
'nameClaim' => 'name',
'emailClaim' => 'email',
'logOut' => false,
'active' => true,
'clientId' => '406547291660-e95je7hamr7nr6p4r7iq2d7tvqo61n85.apps.googleusercontent.com',
'clientSecret' => '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',
'code' => 'go',
'label' => array( 'text' => 'Google',
'type' => 0 ),
'name' => 'google',
'pictureUrlClaim' => '',
'type' => '%google' ) ),
'sessionControl' => array( 'lifeTime' => 15,
'sessionName' => 'Pnk7Wyy16cn85iL11TxF',
'JWTSecret' => 'MKaMULSwRy9Av3PNJpoJ',
'forceExpire' => true,
'keepAlive' => false,
'warnExpire' => true ),
'registration' => array( 'passwordValidation' => array( 'strong' => false,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => false ),
'remindMethod' => 0,
'hashAlgorithm' => 0,
'adminEmail' => 'admin@fhadd.com',
'changePasswordPage' => true,
'changePwdPage' => true,
'notifyAdmin' => true,
'notifyUser' => true,
'registerPage' => true,
'remindPage' => true,
'remindPasswordPage' => true,
'sendActivationLink' => true ),
'captchaSettings' => array( 'captchaType' => 0,
'siteKey' => '',
'secretKey' => '',
'passesCount' => 5 ),
'emailSettings' => array( 'fromEmail' => 'admin@fhadd.com',
'usePHPDefinedSMTP' => false,
'useBuiltInMailer' => false,
'SMTPServer' => 'mail.fhadd.com',
'SMTPPort' => 465,
'SMTPUser' => 'admin@fhadd.com',
'SMTPPassword' => 'Fu@d1982',
'securityProtocol' => 1 ),
'advancedSecurity' => array( 'allowGuestLogin' => false ),
'auditAndLocking' => array( 'loggingTable' => array( 'connId' => 'fhaddcom_finance_at_localhost',
'table' => 'finance_management_audit' ),
'lockingTable' => array( 'connId' => 'fhaddcom_finance_at_localhost',
'table' => 'finance_management_locking' ),
'tables' => array( 'tbl_budgets' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tbl_categories' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tbl_expenses' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tbl_income' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tbl_users' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ) ),
'loggingMode' => 1,
'loggingFile' => 'audit.log',
'logSecurityActions' => true,
'lockAfterUnsuccessfulLogin' => true,
'enableLocking' => true ),
'twoFactorSettings' => array( 'available' => false,
'required' => false,
'enable' => true,
'remember' => true,
'types' => array(  ),
'twoFactorField' => '',
'emailField' => '',
'phoneField' => '',
'codeField' => '',
'projectName' => '' ),
'projectName' => 'finance',
'loginDataSource' => 'tbl_users',
'loginForm' => 0,
'dynamicPermissions' => false,
'dpTablePrefix' => '',
'dpTableConnId' => 'fhaddcom_finance_at_localhost',
'hardcodedLogin' => false,
'enabled' => true,
'advancedSecurityAvailable' => true,
'userGroupsAvailable' => true,
'defaultProviderCode' => '00',
'adOnlyLogin' => false,
'dbProvider' => array( 'type' => '%db',
'activationField' => 'active',
'active' => true,
'code' => '00',
'emailField' => 'email',
'extUserIdField' => 'ext_security_id',
'fullnameField' => 'fullname',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'resetDateField' => '˂Create new˃',
'resetTokenField' => '˂Create new˃',
'table' => array( 'connId' => 'fhaddcom_finance_at_localhost',
'table' => 'tbl_users' ),
'userGroupField' => 'ID',
'usernameField' => 'username',
'userpicField' => 'userpic' ),
'adAdminGroups' => array(  ),
'showUserSource' => true,
'dbProviderCodes' => array( '00',
'go' ),
'notifications' => array(  ) );
?>